// Code generated by foundation httpcontract; DO NOT EDIT.

package naverr

import (
	"sort"

	"github.com/yueli-official/foundation/go/problem"
)

const (
	CodeAuthorizationUnavailable = "nav.authorization_unavailable"
	CodeConflict                 = "nav.conflict"
	CodeForbidden                = "nav.forbidden"
	CodeInvalidInput             = "nav.invalid_input"
	CodeMembershipSuspended      = "nav.membership_suspended"
	CodeMembershipUnavailable    = "nav.membership_unavailable"
	CodeNotFound                 = "nav.not_found"
	CodeNotInitialized           = "nav.not_initialized"
	CodePreconditionRequired     = "nav.site_profile_precondition_required"
	CodeRevisionConflict         = "nav.site_profile_revision_conflict"
)

var descriptors = map[string]problem.Descriptor{
	CodeAuthorizationUnavailable: descriptor(CodeAuthorizationUnavailable, 503),
	CodeConflict:                 descriptor(CodeConflict, 409),
	CodeForbidden:                descriptor(CodeForbidden, 403),
	CodeInvalidInput:             descriptor(CodeInvalidInput, 400),
	CodeMembershipSuspended:      descriptor(CodeMembershipSuspended, 403),
	CodeMembershipUnavailable:    descriptor(CodeMembershipUnavailable, 503),
	CodeNotFound:                 descriptor(CodeNotFound, 404),
	CodeNotInitialized:           descriptor(CodeNotInitialized, 503),
	CodePreconditionRequired:     descriptor(CodePreconditionRequired, 428),
	CodeRevisionConflict:         descriptor(CodeRevisionConflict, 412),
}

func descriptor(code string, status int) problem.Descriptor {
	return problem.MustDescriptor(problem.MustKind(code, status), "https://errors.yueli.dev/problems/"+code)
}

func DescriptorForCode(code string) (problem.Descriptor, bool) {
	value, ok := descriptors[code]
	return value, ok
}

type CatalogEntry struct {
	Code   string `json:"code"`
	Status int    `json:"status"`
}

func Catalog() []CatalogEntry {
	result := make([]CatalogEntry, 0, len(descriptors))
	for code, value := range descriptors {
		result = append(result, CatalogEntry{Code: code, Status: value.Kind().Status()})
	}
	sort.Slice(result, func(i, j int) bool { return result[i].Code < result[j].Code })
	return result
}
