/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CollectionCard: typeof import('./components/CollectionCard.vue')['default']
    MobileHeader: typeof import('./components/MobileHeader.vue')['default']
    ModifyCategory: typeof import('./components/ModifyCategory.vue')['default']
    ModifyCollection: typeof import('./components/ModifyCollection.vue')['default']
    ModifyGroup: typeof import('./components/ModifyGroup.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheFooter: typeof import('@yuelioi/ui')['TheFooter']
    YamiDialog: typeof import('@yuelioi/ui')['YamiDialog']
  }
}
